name: cma 
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.2.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - lightning=2.0.6 
  - tqdm=4.66.1
  - pandas=2.0.3
  - polars=0.18.11
  - numpy=1.25.2
  - transformers=4.31.0
  - tensorboard=2.14.0
  - hydra-core
  - scikit-learn
  - plotly
  - kaleido
  - pip:
    - git+https://github.com/neelnanda-io/TransformerLens


    
