seed: 62

model:
  name: GroNLP/gpt2-small-dutch
  components_path: components
  components: random

data:
  path: data
  name: bug
  workers: 4
  val_size: 0.2

tuner:
  epochs: 10
  lr: 1E-4
  warmup: 0
  eps: 1e-8
  momentum: 0.9
  weight_decay: 1E-4
  batch_size: 32
  checkpoint_path: checkpoints
  results_path: /content/drive/My Drive/Mitigation_data
  ID_path: ID2_100ep
  